const income=100;
const spend=40;
console.log(income-spend);
const totalPencil=10;
const usedPencil=2;
console.log(totalPencil-usedPencil);
const moneyHas=60;
const eachSpend=15;
console.log(moneyHas/eachSpend);
const firstPart="Hello";
const secondPart="World";
console.log(firstPart+secondPart);
const purchase1=153;
const purchase2=261;
console.log(purchase1+purchase2);
const ihave=500;
const prottekbar=75;
console.log(ihave/prottekbar);
console.log(ihave%prottekbar);
console.log(8/3,8%3);
console.log(50/9,50%9);
console.log("Bangla"+"desh");
console.log(480/4);
console.log(480/(4*30));