let age= 21;
console.log(age);
age=24;
console.log(age);
let pocketMoney=500;
pocketMoney=150;
console.log(pocketMoney);
let studyTime=4;
studyTime=6;
console.log(studyTime);
let friendsCount=3;
friendsCount=friendsCount-2;
console.log(friendsCount);
let phonePrice=25000;
phonePrice=12000;
console.log(phonePrice);
let chairsCount=40;
chairsCount=chairsCount-2;
chairsCount=chairsCount-6;
console.log(chairsCount);
let playTime=3;
playTime=0;
console.log(playTime);
