const myage=15;
const brotherAge=10;
console.log(myage<=brotherAge);
const passMarks=33;
const myMarks=45;
console.log(passMarks<myMarks);
const jambura=250;
const kodbel=120;
console.log(jambura<kodbel);
const myReading=10;
const friendReading=10;
console.log(myReading==friendReading);
const myNumberBiscuits=15;
const friendsNumberBiscuits=20;
console.log(myNumberBiscuits<friendsNumberBiscuits);
const  RealMadridScore=2;
const  BarcelonaScore=3;
console.log(RealMadridScore<BarcelonaScore);
const myName="Rahim";
const friendName="Karim";
console.log(myName==friendName);
const meStudy=true;
const friendStudy=false;
console.log(meStudy==friendStudy);